name: zaza
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: 0.18.1
  get: ^3.24.0
  global_configuration: ^1.6.0
  http: ^0.12.2
  dio: ^3.0.10
  cached_network_image: ^2.3.2+1
  carousel_slider: ^2.2.1
  jwt_decoder: ^1.0.4
  get_storage: ^1.4.0
  url_launcher: ^5.7.10
  location: ^3.2.4
  image_picker: ^0.6.7+22




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/images/circle_drawable.svg
    - assets/images/line_separater.svg
    - assets/images/ic_access_time_24px.svg
    - assets/images/price-tag.svg

    - assets/images/item1.svg
    - assets/images/item2.svg
    - assets/images/item3.svg
    - assets/images/item4.svg

    - assets/images/btn_bg.svg
    - assets/images/sign_in_btn_bg.svg
    - assets/images/support.svg

    - assets/images/delivery_guy.svg
    - assets/images/house.svg
    - assets/images/arrows.svg
    - assets/images/discount.svg
    - assets/images/loading.gif
    - assets/images/logo.png
    - assets/images/ic_fiber_new_24px.svg
    - assets/images/ic_pick_up.svg
    - assets/images/ic_delivery.svg
    - assets/images/mob_icon.svg
    - assets/images/pwd_icon.svg
    - assets/images/waiter.svg
    - assets/images/order.svg
    - assets/images/menu.svg
    - assets/images/ic_call_24px.svg
    - assets/images/ic_star_24px.svg
    - assets/images/ic_help_outline_24px.svg
    - assets/images/ic_perm_contact_calendar_24px.svg
    - assets/images/cart.svg

    - assets/images/ic_bookmark_border_24px.svg

    - assets/images/bacground.png
    - assets/images/2.0x/bacground.png
    - assets/images/3.0x/bacground.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
